# Root config — loaded by all child units via find_in_parent_folders("root.hcl")
#
# Directory hierarchy: <account>/<region>/<environment>/<module>/terragrunt.hcl
# Three config layers resolved via find_in_parent_folders():
#   account.hcl  → account_name, optional account_id
#   region.hcl   → Alibaba Cloud region
#   env.hcl      → environment name, project name

locals {
  # ── 3-layer config ──────────────────────────────────────────────────────────
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  env_vars     = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  # Account
  account_name = local.account_vars.locals.account_name
  account_id   = try(local.account_vars.locals.account_id, "")

  # Region
  region = local.region_vars.locals.region

  # Environment
  env     = local.env_vars.locals.environment
  project = local.env_vars.locals.project

  # Remote state bucket (OSS). Same formula as oss stack: <project>-tfstate
  state_bucket = "${local.project}-tfstate"
}

# ── Remote State ──────────────────────────────────────────────────────────────
# Terraform Alibaba Cloud OSS backend.
# See: https://developer.hashicorp.com/terraform/language/backend/oss
#
# Prerequisites:
#   • Create the OSS bucket once (Console or aliyun oss mb). Name: <project>-tfstate
#     (see local.state_bucket, e.g. alicloud-modules-tfstate). Enable versioning recommended.
#   • Auth via ALICLOUD_ACCESS_KEY / ALICLOUD_SECRET_KEY / ALICLOUD_REGION (see repo
#     root env.sh.example). Do not hardcode secrets in HCL.
#   • Optional locking: configure tablestore_endpoint / tablestore_table in config.
#
# Modules with dependency { } blocks resolve outputs via each dependency's backend.
#
# State key layout: <region>/<environment>/<path_relative_to_include>/terraform.tfstate
remote_state {
  backend = "oss"

  # Do not set disable_init = true: older Terragrunt passed -backend=false to terraform init,
  # so the backend was never initialized and terraform output failed on dependencies.

  # When false (default), Terragrunt uses a fast path that only reads remote_state and
  # runs terraform output on dependencies — mock_outputs for plan/validate are not applied.
  disable_dependency_optimization = true

  config = {
    bucket = local.state_bucket
    key    = "${local.region}/${local.env}/${path_relative_to_include()}/terraform.tfstate"
    region = local.region
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# Re-run init against the generated backend when backend.tf or state config changes (avoids
# "Backend initialization required" after cache churn or remote_state edits).
terraform {
  extra_arguments "init_reconfigure" {
    commands  = ["init"]
    arguments = ["-reconfigure"]
  }
}

# ── Provider Generation ────────────────────────────────────────────────────────
# Generates provider_tg.tf with region from region.hcl.
# Provider version constraints stay in each module's versions.tf.
#
# Authentication (env vars — do not hardcode secrets):
#   ALICLOUD_ACCESS_KEY
#   ALICLOUD_SECRET_KEY
#   ALICLOUD_REGION          (should match region.hcl)
# Optional:
#   ALICLOUD_SECURITY_TOKEN
#   ALICLOUD_ASSUME_ROLE_ARN
# See repo root env.sh.example.
generate "provider" {
  path      = "provider_tg.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOT
    # Generated by Terragrunt — do not edit manually.
    # Provider version constraints live in the module's versions.tf.
    # Credentials come from ALICLOUD_ACCESS_KEY / ALICLOUD_SECRET_KEY / ALICLOUD_REGION.
    provider "alicloud" {
      region = "${local.region}"
    }
  EOT
}

# ── Shared inputs ─────────────────────────────────────────────────────────────
# Merged (deep) with _envcommon/*.hcl and per-environment terragrunt.hcl.
inputs = {
  project     = local.project
  environment = local.env
  tags = {
    Project     = local.project
    Environment = local.env
    Account     = local.account_name
    Region      = local.region
    ManagedBy   = "terraform"
  }
}
